name: Manual Test

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run hello.py
        run: python hello.py

      - name: Upload output artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-output
          path: output.txt


